\connect hfpdb;
BEGIN;
TRUNCATE hfp.staging;
\copy hfp.staging FROM ../rawdata/tidy/hsl_tram_geo4_tidy_2019-06-03.csv CSV HEADER;
\copy hfp.staging FROM ../rawdata/tidy/hsl_tram_geo4_tidy_2019-06-04.csv CSV HEADER;
\copy hfp.staging FROM ../rawdata/tidy/hsl_tram_geo4_tidy_2019-06-05.csv CSV HEADER;
\copy hfp.staging FROM ../rawdata/tidy/hsl_tram_geo4_tidy_2019-06-06.csv CSV HEADER;
\copy hfp.staging FROM ../rawdata/tidy/hsl_tram_geo4_tidy_2019-06-07.csv CSV HEADER;
\copy hfp.staging FROM ../rawdata/tidy/hsl_tram_geo4_tidy_2019-06-08.csv CSV HEADER;
\copy hfp.staging FROM ../rawdata/tidy/hsl_tram_geo4_tidy_2019-06-09.csv CSV HEADER;
\i 01_staging_to_points.sql;
TRUNCATE hfp.staging;
COMMIT;
